import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import WinBar from '../components/WinBar';
import TopReasons from '../components/TopReasons';
import SegmentsTabs from '../components/SegmentsTabs';
import EvidenceTrace from '../components/EvidenceTrace';
import { copyMarkdownSummary } from '../lib/summary';
import DriverCards from '../components/DriverCards';
export default function ResultsView() {
    const [data, setData] = useState(null);
    useEffect(() => {
        fetch('/mock/result.json').then(r => r.json()).then(setData);
    }, []);
    if (!data)
        return _jsx("main", { className: "max-w-6xl mx-auto p-6", children: "Loading\u2026" });
    return (_jsxs("main", { className: "max-w-6xl mx-auto p-6 space-y-6", children: [_jsxs("header", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold", children: "Experiment Results" }), _jsxs("div", { className: "mt-1 flex flex-wrap gap-2", children: [_jsx("span", { className: "chip", children: data.city }), _jsxs("span", { className: "chip", children: ["Sample ", data.sample_n] }), _jsxs("span", { className: "chip", children: ["Confidence ", data.aggregate.confidence] })] })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("a", { className: "btn btn-secondary", href: `about:blank?title=${encodeURIComponent('Create Jira tasks for ' + data.experiment_id)}`, target: "_blank", rel: "noreferrer", children: "Create Jira Tasks" }), _jsx("a", { className: "btn btn-secondary", href: `about:blank`, target: "_blank", rel: "noreferrer", children: "Share to Figma" }), _jsx("button", { className: "btn btn-primary", onClick: () => navigator.clipboard.writeText(copyMarkdownSummary(data)), children: "Copy summary" })] })] }), _jsxs("section", { className: "card p-4 space-y-2", children: [_jsx("h2", { className: "text-xl font-semibold mb-2", children: "Aggregate results" }), _jsx(WinBar, { A: data.aggregate.A, B: data.aggregate.B, tie: data.aggregate.tie })] }), _jsxs("section", { className: "grid md:grid-cols-2 gap-4", children: [_jsxs("div", { className: "card p-4", children: [_jsx("h3", { className: "font-semibold mb-2", children: "Top reasons" }), _jsx(TopReasons, { reasons: data.top_reasons }), _jsx(EvidenceTrace, { drivers: data.drivers })] }), _jsxs("div", { className: "card p-4", children: [_jsx("h3", { className: "font-semibold mb-2", children: "Recommended actions" }), _jsx("ul", { className: "list-disc pl-5 space-y-1", children: data.recommended_actions.map((x, i) => (_jsx("li", { children: x }, i))) })] })] }), _jsxs("section", { className: "card p-4", children: [_jsx("h3", { className: "font-semibold mb-2", children: "Segments" }), _jsx(SegmentsTabs, { segments: data.segments })] }), _jsx(DriverCards, { d: data.drivers }), _jsxs("section", { className: "card p-4", children: [_jsx("h3", { className: "font-semibold mb-2", children: "Per-twin console" }), _jsx("div", { className: "overflow-auto", children: _jsxs("table", { className: "min-w-full text-sm", children: [_jsx("thead", { className: "text-gray-300", children: _jsxs("tr", { children: [_jsx("th", { className: "text-left p-2", children: "Twin" }), _jsx("th", { className: "text-left p-2", children: "Winner" }), _jsx("th", { className: "text-left p-2", children: "Reason" })] }) }), _jsx("tbody", { children: data.twins.map((t, i) => (_jsxs("tr", { className: "border-t border-[#232838]", children: [_jsx("td", { className: "p-2", children: t.id }), _jsx("td", { className: "p-2", children: t.winner }), _jsx("td", { className: "p-2", children: t.reason })] }, i))) })] }) })] })] }));
}
